export const allInstruments = JSON.parse`[
  {"id":"f26c8ffd-9dbd-4a16-b3e2-c2c9178f3f4e",
"name":"Carlo Robelli CRC94134X C941N 3/4 Size Classical Acoustic Guitar",
"price":112.42,
"description":"3/4-Size Classical Guitar with a Linden Top and Agathis Back/Sides-23.23 -Scale Okume Neck with Comfortable C Profile - Maple Bridge & 19-Fret Fingerboard - Country of Origin: CHINA",
"image":["https://m.media-amazon.com/images/I/518pm5slF0S._AC_SL1200_.jpg","https://m.media-amazon.com/images/I/41MWTAVfGcS._AC_SL1200_.jpg", "https://m.media-amazon.com/images/I/6151Ra+6P0S._AC_SL1200_.jpg"],
"stock":18,
"color":"Yellow",
"categorie":"String",
"brand":"Carlo Robelli",
"location": "United States of America, Arizona",
"status" : "New"},

{"id":"9a73ed54-c47c-4e81-94d2-ce850c8f4aba",
"name":"Ibanez AEG5012 AEG Series Single-Cutaway 12-String Acoustic-Electric Guitar",
"price":235.45,
"description":"Ergonomics: Features a small and simple preamp that has only two control knobs, volume, and shape Tone Control: At-a-glance tone control offers natural acoustic sound - Versatility: Enables the players to go from low, fat and powerful tones - Mechanism: Easy-to-read onboard tuner with LCD (liquid crystal display) for clear readibility - Purpleheart: Produces a rich mid-range with a crisp high end",
"image":["https://m.media-amazon.com/images/I/61EE5GvN0pL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71zqDMHf6gL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/61Cmi6FXNJL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71cTkfNhZ2L._AC_SL1500_.jpg"],
"stock":17,
"color":"Black",
"categorie":"String",
"brand":"Ibanez",
"location": "United States of America, Arizona",
"status" : "New"},

{"id":"17c2020e-bdad-4ab6-9c49-733030e50866",
"name":"Takamine GJ72CE-12NAT Jumbo Cutaway 12-String Acoustic-Electric Guitar",
"price":156.99,
"description":"Solid spruce top and flame maple back and sides - Produces all the lush, robust sound that players expect from a jumbo 12-string guitar - Slim mahogany neck and 12' -radius bound rosewood fingerboard provide great feel and playability - Taka mine TK-40D preamp system gives you a built-in tuner, three-band EQ and gain controls, mid contour switch, notch filter and EQ bypass switch for the ultimate in versatility and sound quality - Elegant Natural gloss finish",
"image":["https://m.media-amazon.com/images/I/31K13fWB7WL._AC_.jpg", "https://m.media-amazon.com/images/I/51SwkszUxuL._AC_.jpg", "https://m.media-amazon.com/images/I/51Eadc+G3xL._AC_SL1000_.jpg", "https://m.media-amazon.com/images/I/51DYYr1Rr0L._AC_.jpg"],
"stock":19,
"color":"Natural",
"categorie":"String",
"brand":"Takamine",
"location": "United States of America, Arizona",
"status" : "New"},

{"id":"300",
"name":"Yamaha GigMaker Standard Acoustic Guitar w/ Gig Bag, Tuner, Strap and Picks - Sunburst",
"price":98.39,
"description":"The perfect package for beginers with everything you need to get started - Includes an F32D5 Tobacco Sunburst acoustic guitar, gig bag, digital tuner, strap and picks - Dreadnought Body - Spruce Top - Rosewood Fingerboard",
"image":["https://m.media-amazon.com/images/I/71xPqX2lWkL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/81+7+RsbvGL._AC_SL1500_.jpg"],
"stock":19,
"color":"Tobacco Sunburst",
"categorie":"String",
"brand":"Yamaha",
"location": "United States of America, Arizona",
"status" : "Used"},

{"id":"1",
"name":"Fender Fullterton Jazzmaster Concert Ukulele, Walnut Fingerboard, Olympic.",
"price":49.99,
"description":"Jazzmaster body shape - 4-in-line painted Jazzmaster headstock - Fender-designed preamp system - -No-tie bridge - Nickel hardware - Does not include gig bag, but fits into a Fender FU610 Tenor Ukulele Gig Bag",
"image":["https://m.media-amazon.com/images/I/61D3CfFAMBL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71SkpTNRLzL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/711rfmguu9L._AC_SL1500_.jpg","https://m.media-amazon.com/images/I/71NmwjHE8QL._AC_SL1500_.jpg"],
"stock":19,
"color":"White",
"categorie":"String",
"brand":"Fender",
"location": "United States of America, Arizona",
"status" : "Used"},

{"id":"198",
"name":"Acoustic Violin 4/4 Full Size with Bow, Rosin and Carrying Case",
"price":129.99,
"description":"A GREAT VIOLIN FOR BEGINNERS: The beginner violin is an ideal stringed musical instrument for any student who has dreams of playing music. The set includes all the necessities to start learning how to play. - NEW AND HIGH QUALITY:4/4 full size, the head, back and sides are all made from basswood, the fingerboard, tailpiece, pegs, and chin rest are made from plastic, the bow is made from arbor and white horse tail. - INEXPENSIVE AND HIGH-QUALITY AFTER-SALES: If you find any quality problems after purchase, you can return it and repair it for free within 12 months. - THE INSIDE OF CASE IS VERY SOFT: it can protect your violin well, and it is not afraid of carrying damage. - HANDLE WITH CARE: The violin fiddle kit, like most band & orchestra musical instruments, is delicate. Please note the bridge will not be setup to avoid damage during shipping. NOTE: Tuning pegs must be handled with care and pushed in when adjusting.",
"image":["https://m.media-amazon.com/images/I/61M55CXfeUL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/61LGZTnDK2L._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/61PhoPoddlL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/61eCxXKNwFL._AC_SL1500_.jpg"],
"stock":19,
"color":"Natural",
"categorie":"String",
"brand":"Generic",
"location": "United States of America, Arizona",
"status" : "New"},

{"id":"200",
"name":"Tall Celtic Irish Harp 22 Strings Lever Solid Wood with Dulex Bag",
"price":59.99,
"description":"Nylon Strings Harp Metal hardware Solid Wood - Hand Made and Painted - Delux carrying Case - Extra Set of Strings and Tuning Key",
"image":["https://m.media-amazon.com/images/I/71kudj+4jRL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71lttY5Z6oL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71mqbqDOuGL._AC_SL1500_.jpg"],
"stock":3,
"color":"Black",
"categorie":"String",
"brand":"Sturgis",
"location": "Colombia, Bogota ",
"status" : "New"},

{"id":"109",
"name":"Ibanez M522SBS F-Style Mandolin",
"price":139.98,
"description":"Body Shape: F-Style - Neck: Mahogany Neck - Backsides: Flamed Maple Back and Sides - GtrTop: Solid Spruce Top - Tuners: Gold Die-Cast Tuners w/ Pearloid Knobs",
"image":["https://m.media-amazon.com/images/I/91wZtHBrY-L._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71mqbqDOuGL._AC_SL1500_.jpg"],
"stock":3,
"color":"Brown",
"categorie":"String",
"brand":"Ibanez",
"location": "Colombia, Bogota ",
"status" : "Used"},

{"id":"1123",
"name":"Premium Arabic Oud Ud Aoud SALA-A9",
"price":899,
"description":"Measurements: Bridge To Nut: 60 cm | Bowl 51cm - Wenge And Pamela Bowl | Canadian Cedar Face - Ebony fingerboard | Ebony Pegs - It comes with: Extra strings, Plectrum Soft Case",
"image":["https://m.media-amazon.com/images/I/71smStScIPS._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71xK2Sssu2S._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/61oyn6MKcYS._AC_SL1500_.jpg"],
"stock":3,
"color":"Brown",
"categorie":"String",
"brand":"Sala Muzik",
"location": "Colombia, Bogota ",
"status" : "New"},

{"id":"90",
"name":"Naad NS-09 Professional Sarod Ali Akbar Khan Style Tun Wood Sarod",
"price":199.99,
"description":"BRAND NEW HAND MADE INDIAN MUSICALS INSTRUMENT SAROD - SUPER FINE QUALITY - MELODY STRING PEGS 4 PCS &JAWARI PEGS 4 PCS - MUSICAL SAROD - ALI AKBER KHAN STYLE",
"image":["https://m.media-amazon.com/images/I/31CsxOnIl6L._AC_.jpg", "https://m.media-amazon.com/images/I/31-BZ+6tpqL._AC_.jpg", "https://m.media-amazon.com/images/I/31gErY63SML._AC_.jpg"],
"stock":3,
"color":"Brown",
"categorie":"String",
"brand":"Naad",
"location": "Colombia, Bogota ",
"status" : "New"},


{"id":"121",
"name":"Separable Vertical Bamboo Flute Key G Traditional Chinese Xiao",
"price":129.99,
"description":"8 holes G key Flute (xiao) Material: Strictly selected old bamboo(Phyllostachys nigra ) for more than 3 years, dried for more than 3 years - Tuning: The master has more than 3 professional tuning, the tone is thick and crisp, melodious and bright, easy to learn to play it - Mouthpiece: Hand-finished opening, careful modulation, rounded aperture - Tie wire: hand-tie the wire to prevent cracking and prolong the service life. The black line increases the anti-skid property of the flute and its rich quality. - Flute(Xiao) hole: precise adjustment by manual technicians, more than 3 times of tuning, the sound is bright",
"image":["https://m.media-amazon.com/images/I/51OUdTdfoRL._AC_SL1000_.jpg", "https://m.media-amazon.com/images/I/619ULqzBFLL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/81LbBXf-CdL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/61lX5ongOZL._AC_SL1500_.jpg"],
"stock":3,
"color":"Brown",
"categorie":"Wind",
"brand":"MoonAngel",
"location": "Mexico, Mexico City ",
"status" : "Used"},

{"id":"156",
"name":"15 Pipes Brown Pan Flute G Key Chinese Traditional (Right-Hand)",
"price":13.99,
"description":"Color: Brown; Key: G - handmade and high quality - Pipes Number: 15 Pipes - Material: bamboo - performance, woodwind instrument",
"image":["https://m.media-amazon.com/images/I/61og6X952tL._AC_SL1200_.jpg", "https://m.media-amazon.com/images/I/61LARog8AhL._AC_SL1200_.jpg", "https://m.media-amazon.com/images/I/61z3oRwx1oL._AC_SL1200_.jpg", "https://m.media-amazon.com/images/I/71zLAQWEwWL._AC_SL1200_.jpg"],
"stock":3,
"color":"Brown",
"categorie":"Wind",
"brand":"SUTILA",
"location": "Mexico, Mexico City ",
"status" : "New"},

{"id":"2",
"name":"Yamaha YRS-24B Plastic Soprano Recorder, Natural",
"price":35.99,
"description":"Excellent tuning and sound quality - Made from durable and safe ABS plastic resin with no BPA - Double holes for low C/C number and D/D number to improve tuning - Simplified German fingering - Includes cotton carrying bag and fingering chart - Easy to play with a soft pure toneeal amount of air resistance for easy control and accurate intonation - Key of C - Great for beginnersyle fingering (as indicated by “G” stamped packaging)",
"image":["https://m.media-amazon.com/images/I/71jsNLQnXBL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/61Ua5+KwEsL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/51+eqikFQ2L._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/51JFUZ6BEAL._AC_SL1500_.jpg"],
"stock":3,
"color":"Natural",
"categorie":"Wind",
"brand":"Yamaha",
"location": "Mexico, Mexico City ",
"status" : "New"},

{"id":"178",
"name":"Jupiter Bb Bass Clarinet with One Section Wood Frame Case, JBC1000NC",
"price":205.99,
"description":"Jupiter Intermediate Bass Clarinet - Two Piece Durable ABN Resin (Plastic) Body -- Low Eb Key on Body - .945' Bore -- Forged Nickel Silver Plateau Keys -- Undercut Tone Holes - In-Line Trill Keys -- Adjustable Floor Peg -- Adjustable Thumb Rest -- Leather Pads - Includes One-Piece Case and Mouthpiece",
"image":["https://m.media-amazon.com/images/I/319RIeM5XUL._AC_.jpg"],
"stock":3,
"color":"Silver",
"categorie":"Wind",
"brand":"Jupiter",
"location": "Mexico, Mexico City ",
"status" : "Used"},

{"id":"3",
"name":"HOHNER 560PBXC Special 20 Diatonic Harmonica, C-major",
"price":54.99,
"description":"Played By The Pros - Professional Level Instrument - Responsive Reeds - Injection Molded Plastic Comb With Projecting Mouthpiece For Added Playing Comfort",
"image":["https://m.media-amazon.com/images/I/517RthNxXmL._AC_SL1203_.jpg", "https://m.media-amazon.com/images/I/51S1xwfShbL._AC_SL1000_.jpg", "https://m.media-amazon.com/images/I/511w-7oKSSL._AC_SL1000_.jpg", "https://m.media-amazon.com/images/I/51naBAgH68L._AC_SL1200_.jpg"],
"stock":3,
"color":"Silver",
"categorie":"Wind",
"brand":"Honner",
"location": "Mexico, Mexico City ",
"status" : "New"},

{"id":"4",
"name":"Jean Paul USA AS-400SP Student Alto Saxophone",
"price":699.95,
"description":"Silver Plated - Rico H Ligature & Cap - Bari Mouthpiece - Professional Carrying Case - Included Accessories: Quality Neck strap and Care Kit",
"image":["https://m.media-amazon.com/images/I/71TqmLVvK1L._AC_SL1200_.jpg", "https://m.media-amazon.com/images/I/61vG7FmE8mL._AC_SL1200_.jpg", "https://m.media-amazon.com/images/I/61b+GpWSc4L._AC_SL1200_.jpg", "https://m.media-amazon.com/images/I/71nqbfE7fiL._AC_SL1200_.jpg"],
"stock":3,
"color":"Silver",
"categorie":"Wind",
"brand":"Jean Paul USA",
"location": "Mexico, Mexico City ",
"status" : "New"},

{"id":"5",
"name":"White Folding Professional Armenian DUDUK - 3 Reeds,Wooden case - Key A Oboe Balaban",
"price":139.95,
"description":"Our duduks are made from high quality Apricot Wood - Instrument Key: A - The size of the duduk with reed is 17.7 inches (45 cm) - The package includes: Folding Duduk, 3 reeds, beautiful white wooden case, Playing Instruction - DO NOT tear off the leather part of Reed. The reed will stop being usable.",
"image":["https://m.media-amazon.com/images/I/81Ctwvv0LPL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71WDV0iD9qL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/81LCVjzxyqL._AC_SL1500_.jpg"],
"stock":3,
"color":"White",
"categorie":"Wind",
"brand":"HandCraftoria",
"location": "Mexico, Mexico City ",
"status" : "New"},


{"id":"6",
"name":"Pacific Drums Center Stage Complete Drumkit, 5 Drum Set, Diamond White Sparkle, 7x10, 8x12, 14x16 Floor, 16x22 Kick, 5x14 Snare (PDCE2215KTDW)",
"price":599.99,
"description":"Hardware Includes Kick Drum Pedal, Hi-Hat Stand, Cymbal Stand, Snare Stand and Throne - Brass Cymbals Include 13 Crash/Ride - True-Pitch Tension Rods - Sparkle Finishes - Telescoping Kick Drum Spurs - Hand orientation: Ambidextrous",
"image":["https://m.media-amazon.com/images/I/81Ctwvv0LPL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71WDV0iD9qL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/81LCVjzxyqL._AC_SL1500_.jpg"],
"stock":3,
"color":"Diamond White Sparkle",
"categorie":"Percussion",
"brand":"Pacific Drums",
"location": "Argentina, Buenos Aires ",
"status" : "New"},

{"id":"7",
"name":"TAMA Cocktail-JAM Mini 4-Piece 14' bass Drum Shell Pack (CJP44HBK)",
"price":449.99,
"description":"Sound Focus Pad - Specially Designed Bags - Cymbal Attachment Kit MCAX5366 Sold Separately - Set-up Expandability",
"image":["https://m.media-amazon.com/images/I/619wtlU5FvL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71Dm2CitZxL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/817-TiV0KSL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71V8R0OAhUL._AC_SL1500_.jpg"],
"stock":3,
"color":"Black",
"categorie":"Percussion",
"brand":"Tama",
"location": "Argentina, Buenos Aires ",
"status" : "New"},

{"id":"8",
"name":"Yamaha Tour Custom Maple 14' x 6.5' Snare Drum",
"price":249.99,
"description":"All U. S. Maple shells give tour custom drums their warm and bright tone - Shells are designed with a 6 ply-5. 6 mm/ 45 degree bearing edge that adds the tonal depth, quick response and provides just the right amount of sustain - Newly designed 2. 3mm Inverse Dyna hoop controls the natural overtones inherent to all-maple drums and focuses the fundamental tone of the shell - Finished with a beautiful satin lacquer that maximizes the sonic potential of the Maple shell",
"image":["https://m.media-amazon.com/images/I/81SsQF+gJ7L._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/81SsQF+gJ7L._AC_SL1500_.jpg"],
"stock":3,
"color":"Candy Apple Satin",
"categorie":"Percussion",
"brand":"Yamaha",
"location": "Argentina, Buenos Aires ",
"status" : "New"},

{"id":"9",
"name":"Meinl Percussion Meinl VivaRhythm VR-SDSET-NH Boom Series 2-Piece Stack Drum Set, Pre-Tuned Napa Heads, Sunshine Finish",
"price":189.99,
"description":"With 100% synthetic shells and heads, The Mein VivaRhythm stack drum set works great indoors or outside, making them perfect drums For outdoor drum circles, jam sessions, or percussion therapy - 2-Piece set with 9. 5' And 12' Diameter drums - The pre-tuned synthetic Napa heads are designed to deliver a softer, warmer sound - The lightweight synthetic shell delivers a rich, resonant sound that projects in any setting - Provide a strong rhythmic foundation for any setting with the Mein VivaRhythm 2-piece stack drum set",
"image":["https://m.media-amazon.com/images/I/61VAOywhWmL._AC_SL1000_.jpg", "https://m.media-amazon.com/images/I/416xhVTCUlL._AC_.jpg", "https://m.media-amazon.com/images/I/51le6bCe5nL._AC_.jpg"],
"stock":3,
"color":"Sunshine",
"categorie":"Percussion",
"brand":"Meinl Percussion",
"location": "Argentina, Buenos Aires ",
"status" : "New"},

{"id":"10",
"name":"RockJam 7' and 8' Bongo Drum Set with Padded Bag and Tuning Key, Red and Natural Stripe",
"price":36.46,
"description":"Authentic Skin Heads - Chrome Hardware - Head Size: 7 inches and 8 inches - Natural Gloss Finish With Stripe Design - Includes Padded Carry Case and Tuning Key - Note: The skins have to be gradually tightened evenly rather than one side at a time. This can stress both the frame and the skin",
"image":["https://m.media-amazon.com/images/I/81lsvrRChnL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/71GTvqboiaL._AC_SL1500_.jpg", "https://m.media-amazon.com/images/I/810lgmBRU8L._AC_SL1500_.jpg"],
"stock":3,
"color":"Red and Natural Stripe",
"categorie":"Percussion",
"brand":"RockJam",
"location": "Argentina, Buenos Aires ",
"status" : "New"},

{"id":"11",
"name":"Remo DJ-0012-24 Mondo Djembe Drum - Adinkra, 12",
"price":339.95,
"description":"Mondo djembe drum - Package Weight: 15.75 pounds - Package Dimensions: 38.1 L x 72.898 H x 40.386 W (centimeters) - Model No: DJ001224",
"image":["https://m.media-amazon.com/images/I/819lnwOyoaL._AC_SL1500_.jpg"],
"stock":3,
"color":"Adinkra",
"categorie":"Percussion",
"brand":"Remo",
"location": "Argentina, Buenos Aires ",
"status" : "New"},

{"id":"12",
"name":"Shaman drum Cow plain 2', Frame Drum, handmade",
"price":169,
"description":"Shaman drum round covered with cow skin (shorn) - Beater included - Tensioned with skin rope - 20 inch dia - Native American Style, Handmade.",
"image":["https://m.media-amazon.com/images/I/61aBpNCBhvL._AC_SL1024_.jpg","https://m.media-amazon.com/images/I/713J0Drv4NL._AC_SL1024_.jpg", "https://m.media-amazon.com/images/I/717JwmjDE4L._AC_SL1024_.jpg"],
"stock":3,
"color":"Brown",
"categorie":"Percussion",
"brand":"Terre",
"location": "Argentina, Buenos Aires ",
"status" : "New"},
    {
        "id": "50",
        "name": "Drums set Roland",
        "price": 763,
        "descript": "Streamlined and affordable electronic drum kit with acoustic-style looks, shallow-depth shells and TD-07 module",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948583/samples/Instruments/50_eoudls.jpg",
        "stock": 2,
        "color": "Black",
        "categorie": "Percussion",
        "brand": "Roland",
        "location": "Canada, Ottawa ",
        "status" : "New"
      },
    {
        "id": "51",
        "name": "Drum set",
        "price": 599,
        "descript": "The PDP Center Stage drum sets are a killer value, featuring exceptional construction and components as well as a full hardware package. Experience the powerful and smooth low end warmth of these poplar shells. Enjoy the eye-catching appearance and amazing durability of sparkle wrapped finishes. The kit includes a snare, bass drum, floor tom and two rack toms plus a throne, double-braced hardware, brass cymbals and even sticks. True-Pitch tension rods, telescoping spurs and a variety of other features normally reserved for high-end drums make the Center Stage kits perfect for any aspiring player.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948758/samples/Instruments/51_c5cbew.jpg",
        "stock": 3,
        "color": "Brown",
        "categorie": "Percussion",
        "brand": "Pdp",
        "location": "Mexico, Mexico City ",
        "status" : "New"
      },
    {
        "id": "52",
        "name": "Maracas",
        "price": 29,
        "descript": "Tycoon Percussion TMS-70 Rawhide Maracas are the medium version of Tycoon’s rawhide maracas. Perfect for quite to medium volume playing or studio recording use, these maracas are a must have for every percussionist.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660949331/samples/Instruments/52_zasqyk.jpg",
        "stock": 15,
        "color": "Brown",
        "categorie": "Percussion",
        "brand": "Tycoon",
        "location": "Chile, Santiago ",
        "status" : "New"
      },
    {
        "id": "53",
        "name": "Maracas",
        "price": 10,
        "descript": "Latin Percussion Cp 7 1/2 Med. Maracas",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948596/samples/Instruments/53_x8pu0c.jpg",
        "stock": 10,
        "color": "Graphic Art",
        "categorie": "Percussion",
        "brand": "Latin Percussion",
        "location": "Colombia, Bogotá ",
        "status" : "New"
      },
    {
        "id": "54",
        "name": "Xylophone",
        "price": 204,
        "descript": "A very fun activity that even chickens and birds love! this wooden xylophone comes assembled with each key accurately tuned - for playing in harmony with other musical instruments.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948612/samples/Instruments/54_lidoqt.jpg",
        "stock": 4,
        "color": "Black",
        "categorie": "Percussion",
        "brand": "Yamaha",
        "location": "Colombia, Bogotá ",
        "status" : "New"
      },
    {
        "id": "55",
        "name": "Bongos",
        "price": 109,
        "descript": "These surprisingly affordable bongos are offered with beautiful natural wood shell, and feature traditional style black hardware. Features include EZ-Curve rims, tucked heads, tuning wrench, and Cuban style steel bottoms.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948636/samples/Instruments/55_zudtlh.jpg",
        "stock": 12,
        "color": "Wood",
        "categorie": "Percussion",
        "brand": "Latin Percussion",
        "location": "Venezuela, Caracas ",
        "status" : "New"
      },
    {
        "id": "56",
        "name": "Bongos",
        "price": 75,
        "descript": "The Pyle Hand-Crafted Bongo Drums feature hand-crafted wooden shells. Classic and traditional bongo style makes them the perfect pair for beginner and experienced players of all ages. The natural ‘true skin’ animal hide head covers reproduce clean acoustical percussion sounds. Additional bongo features include tune-able heads with chrome-plated hardware, two-toned side panels with glossy finish, along with an included tuning key wrench. Add some sound, and style, with the Pyle Wooden Bongo Drums.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948751/samples/Instruments/56_xfkmxy.jpg",
        "stock": 7,
        "color": "Red",
        "categorie": "Percussion",
        "brand": "Pyle",
        "location": "Canada, Ottawa ",
        "status" : "New"
      },
    {
        "id": "57",
        "name": "Congas",
        "price": 399,
        "descript": "This vintage sunburst finish 28 tall conga wood set comes with a height adjustable double conga stand.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948822/samples/Instruments/57_z7ceat.jpg",
        "stock": 3,
        "color": "Sunburst",
        "categorie": "Percussion",
        "brand": "Latin Percussion",
        "location": "Venezuela, Caracas ",
        "status" : "New"
      },
    {
        "id": "58",
        "name": "Congas",
        "price": 349,
        "descript": "Toca is committed to being Green and environmentally-friendly. The wood used is harvested from a plantation in Thailand, where Toca Drums are then lathed and handcrafted by local musicians. This carefully managed resource is much easier on the environment than wood taken from primary forests.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948670/samples/Instruments/58_kfqfcf.jpg",
        "stock": 8,
        "color": "Brown",
        "categorie": "Percussion",
        "brand": "Toca",
        "location": "United States of America, Arizona",
        "status" : "New"
      },
    {
        "id": "59",
        "name": "Triangle",
        "price": 20,
        "descript": "Tycoon Percussion TRI-10 Triangle is a 10 triangle manufactured from chrome plated tempered steel, this triangle delivers a bright, clean sound when struck with the striker. Matching steel striker and nylon hanging cord included",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948617/samples/Instruments/59_g6qvpn.jpg",
        "stock": 20,
        "color": "Gray",
        "categorie": "Percussion",
        "brand": "Tycoon",
        "location": "United States of America, Washington, D.C. ",
        "status" : "New"
      },
    {
        "id": "60",
        "name": "Tambourine",
        "price": 34,
        "descript": "Traditional Wood Tambourines from the MEINL collection are the perfect choice for ultra-bright, shimmering jingle accents that respond beautifully at any volume level. The sturdy wooden frame delivers a natural, warm attack followed by the sensitive cutting sounds of the jingles with a slight high-pitched sustain. An ergonomic grip gives you total control of the instrument. This model is equipped with nickel plated steel jingles that are among the brightest sounding from MEINL. Their pitch is high, making it easy to cut through and provide a strong rhythmic foundation with other instruments at any volume level. These tambourines are great for percussionists and drummers, but any musician or vocalist will find them extremely useful in their playing as well.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948655/samples/Instruments/60_jglgvt.jpg",
        "stock": 2,
        "color": "Brown",
        "categorie": "Percussion",
        "brand": "Meinl Percussion",
        "location": "Brazil, Brasilia ",
        "status" : "New"
      },
    {
        "id": "61",
        "name": "Piano",
        "price": 399,
        "descript": "If you’re looking for a fun and inspiring way to start playing music, Roland’s GO:KEYS is the answer! With its innovative Loop Mix function, anyone can build fully produced songs right away, even with no previous music experience. There’s also a diverse range of pro sounds to explore, plus an easy-to-use recorder to capture and share your creations. And with Bluetooth connectivity, you can jam along with music from your smartphone or tablet and work with all sorts of great music apps. Compact and battery powered, GO:KEYS lets you enjoy the magic of musical creativity everywhere you go.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660949382/samples/Instruments/61_vfqdjo.jpg",
        "stock": 5,
        "color": "Red",
        "categorie": "Electric",
        "brand": "Roland",
        "location": "Brazil, Brasilia ",
        "status" : "New"
      },
    {
        "id": "62",
        "name": "Piano",
        "price": 90,
        "descript": "The RockJam 54 key keyboard piano is perfect for aspiring pianists of all age groups. This compact, portable, high quality keyboard piano has built-in stereo speakers and a large, easy to read LCD screen that gives you a visual guide when using the integrated teaching tool. The keyboard includes 100 tones and rhythms and a record and playback function that supports up to 41 notes.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948738/samples/Instruments/62_fypaz4.jpg",
        "stock": 9,
        "color": "Black",
        "categorie": "Electric",
        "brand": "RockJam",
        "location": "Brazil, Brasilia",
        "status" : "New"
      },
    {
        "id": "63",
        "name": "Synthesizer",
        "price": 659,
        "descript": "Amazing analog synthesizer with triple VCO design allows for insanely fat music creation",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948768/samples/Instruments/63_w8zfug.jpg",
        "stock": 1,
        "color": "Black",
        "categorie": "Electric",
        "brand": "Behringer",
        "location": "New Zealand, Wellington ",
        "status" : "New"
      },
    {
        "id": "64",
        "name": "Sampler",
        "price": 399,
        "descript": "Roland TR drum machines have impacted music for over 40 years—and they're as influential now as ever. Based on the much-loved TR-8S, the compact and affordable TR-6S has the same speaker-pummelling, window-rattling, body-moving sound of its bigger sibling. Elevate your drum tracks, make beats on the go, and experience the joy of hands-on production. With the TR-6S, the sound of classic tracks, today's trends, and tomorrow's hits are always within reach.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660949498/samples/Instruments/64_jsetnm.jpg",
        "stock": 9,
        "color": "Black",
        "categorie": "Electric",
        "brand": "Roland",
        "location": "Belgium, Brussels ",
        "status" : "New"
      },
    {
        "id": "65",
        "name": "Sampler",
        "price": 99,
        "descript": "Akai Professional’s MPD218 is a MIDI-over-USB pad controller perfect for producers, programmers, musicians and DJs alike. Its intuitive blend of MPC controls and technologies mesh with seamless USB connectivity to bring the feel of classic beat making into the world of computer music production. At the heart of MPD218 are 16 ultra-sensitive, hyper-playable. Thick Fat MPC pads, ideal for triggering drums, one-shots, melodic samples, basslines and more; with 3 pad banks available and a pressure- and velocity-sensitive specification, expand MPD218’s performance capability to 48 fully-assignable, ultra-reactive triggers that capture every subtlety and nuance of your performance.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948620/samples/Instruments/65_anqkvc.jpg",
        "stock": 14,
        "color": "Black",
        "categorie": "Electric",
        "brand": "AKAI",
        "location": "Spain, Madrid",
        "status" : "New"
      },
    {
        "id": "66",
        "name": "Electric Drum",
        "price": 324,
        "descript": "Features: - Hassle-Free Tabletop Drum Kit - Compact, Portable & Ultra-Thin - Unique Roll-Up Design for Instant Drumming - Pre-Loaded with Selectable Drum Kits & Songs - MIDI Support: Connect to Computer & Unlock More - Record Mode: Playback Your Drum Sessions - Hand Percussion Mode: Drop the Drumsticks & Use Your Hands - Effectively Reproduces Complete 'Drum Set' Sounds - (7) Drum Pads with Touch Sensitivity - Tom-Toms, Hi-Hat, Snare & Bass Drums, Crash & Ride Cymbals - Super Easy & Simple USB Plug-in Operation - Includes (2) Digital Foot Pedal Controllers - Front Panel Button Control Center - Built-in Full Range Stereo Speakers - Aux (3.5mm) Input Jack - Drum-Along to Music via Connected Device - Headphone Jack - Tempo & Volume Adjustable - Compatible with Mac & PC What's in the Box: - Electronic Drum Pad - (2) Drum Foot Pedals - USB Cable & Wall Power Adapter - Audio Connection Cable - Drum Sticks Technical Specs: - Drum Kits: (12) Sound Styles - Power Connection: USB 9V - Drum Sticks Dimensions: 0.6’’ x 11.6’’ -inches - Electronic Drum Pad Dimensions: 8” -inches",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948612/samples/Instruments/66_z9zlhz.jpg",
        "stock": 2,
        "color": "Black",
        "categorie": "Electric",
        "brand": "Pyle",
        "location": "Ecuador, Quito ",
        "status" : "New"
      },
    {
        "id": "67",
        "name": "Amplifier",
        "price": 247,
        "descript": "Fender, a leader in instrument manufacturing, started designing, manufacturing and evolving musical instruments in 1946. Since, Fender amplifiers have and continue to be an integral part of modern music. Easy to use and versatile enough for any style of guitar playing, the 40-watt, 1x12” Champion 40 is an ideal choice as your first practice amp and an affordable stage amp. Straightforward controls, cool effects and versatile amp voicings make it easy to dial in just the right sounds for rock, blues, metal, country, jazz and more.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948608/samples/Instruments/67_nhl5gs.jpg",
        "stock": 32,
        "color": "Black",
        "categorie": "Electric",
        "brand": "Fender",
        "location": "Argentina, Buenos Aires ",
        "status" : "New"
      },
    {
        "id": "68",
        "name": "Amplifier",
        "price": 165,
        "descript": "The MG15GR is loaded with pure Marshall tone. You get your choice of Clean and Overdrive channels that you can shape with a 3-band EQ. You also get an integrated digital spring reverb effect. Best of all, each channel's settings are storable and recallable. The MG15GR is loud enough to rattle the windows during practice sessions, while its revolutionary solid-state design convincingly emulates a tube amp's tone and response. Beyond that, the MG15GR supplies you with a line input for music players and emulated headphone and line outputs. Part of Marshall's MG Gold series, the MG15GR is a great-sounding practice amp.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660949134/samples/Instruments/68_bsvhiq.jpg",
        "stock": 14,
        "color": "Black",
        "categorie": "Electric",
        "brand": "Marshall",
        "location": "Argentina, Buenos Aires ",
        "status" : "New"
      },
    {
        "id": "69",
        "name": "Electric Drum",
        "price": 70,
        "descript": "This professional drum set machine and percussion drums has built-in dual stereo speakers, emitting actual drum sounds with astonishing bass effects",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660949274/samples/Instruments/69_rjdkag.jpg",
        "stock": 3,
        "color": "Black",
        "categorie": "Electric",
        "brand": "MAZAHEI",
        "location": "Spain, Madrid ",
        "status" : "New"
      },
    {
        "id": "70",
        "name": "Electric Bass",
        "price": 200,
        "descript": "Don't be fooled into thinking the Ibanez GSR micro is a toy. Its made to the same high standards of the other GIO series guitars. The Gsrm20 features, small scale SR body, full sound pickups, the same construction, same materials, and same set-up and inspection as its full size counterparts. Its shorter 28. 6” scale makes it perfect for tour buses, space-restricted home studios, folks with smaller hands, as well as young rockers or beginners.",
        "image": "https://res.cloudinary.com/deqxuoyrc/image/upload/v1660948582/samples/Instruments/70_cojhil.jpg",
        "stock": 0,
        "color": "Oil",
        "categorie": "Electric",
        "brand": "Ibanez",
        "location": "Ecuador, Quito",
        "status" : "New"
    
      }
    
    
    
    
]`;
